apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: parentinfo
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgANRNEKloSzZNWui+i5abZEozU6kidAL81L4d90TAu8Wq1VxNAtfnKkdC9/az81t6YAMCwGxEltFXiUVype7t6TEmzNGmSv46729a9DiiJ5nb3pXjPywjkO5BkegXwxucSZS8mbIXscNNsPG2aBjgHFi01CFCNAXAYiShmnxWQ9n7pTPhFewC9nIhmieABLEYb+kZoRIdQl009mOgvPdDIvU48EHlJp+uWzNC6LFJl1EnH4ZJuJ/cv6PnmmvN215OkVfuW/kVlZ8sJevGav05skQm4JF16iJnYKQpUlYU+ovRIQD3G5tMWu4jjZhpKYwS1XUNudYQ6PXyVSzjQg39pmJy7DzrA8Uo/L3CMr8mKuUZSw00WIh/PAB9GbD6vaXHmnB6uV/tL9NKRSvSNwYgaqR5t8rDZD+58LrQ9orUk046RTTHpchUw6g1b37wMzz2/mdbK6DnuI7v8hCdoE4fwn+oa3lWLGhCw8sogNMXR6a08qEjMKggHALpmE8xxAvmZ1/P71zZZKoNFYQdTztAE44poPcZcG3qsDNCFlaXZFnHnmopYRxDUCN5JtjKhEroFH2aWhweytoSC1Lp1dYt5yJyCKaDfPxPdpcoGuTvnBxzkC46Sv9y94rXkfZyzSiF4EmT8erS9DB8hUB/3tLXcu3Y3TNAnxeHsZhZW2UBtG3GTlahGEL67Csboqf4AABPonO2PDRKtwI5NApxs+u11Pkh9kC5E9tKtBH5B9+pEtypD6TIieOi7dpP0pSKQPv9eIolk2WAL0IQL/4HBsCn7ZMc6XBdaN/Kclw5M9RALP8POv0EE1jm/yRbi8ptZjTqIqiJj/0zYbcDdrdo2vjABp+RfUafvpGtWVnjzBPmZ3lScKM59r0hGz0BDk2ZpxAjuJxuTJeLeiDTuKGLkaaq5n/77TivkpfGToWeAIMAU4LSXugNzH9SmHuGfH7L2pv/zBToWmwwMlBPPWMcSrAUGYVtepUUFczUuI8jSn57j1y13iE746pv5ByvSqxtudt3d2Ha0K9C4dcbzXmwxOuUmbplS7bpzlkGxiPVyHLWBmduiA/gFxPV8q3pWGgPOnEXU=
  template:
    metadata:
      name: registry-credentials
      namespace: parentinfo
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
